services:
  gateway:
    build:
      context: ./gateway
    networks: [berry]
    hostname: gateway
    depends_on: [founders, companies]
    ports:
      - "4000:7000"

    environment:
      - FOUNDERS_ENDPOINT=http://founders:8000/graphql
      - COMPANIES_ENDPOINT=http://companies:8800/graphql


  founders:
    build:
      context: ./founders
    networks: [berry]
    hostname: founders

  companies:
    build:
      context: ./companies
    networks: [berry]
    hostname: companies

networks:
  berry:
