on:
  push:
    branches:
      - main
    
env:
  RESOURCE_GROUP: "csu-nl-sr-graphql"
jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      registry: ${{ steps.deploy_infra.outputs.registry }}
    steps:
      - uses: actions/checkout@v3
      # - uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - id: step1
      #   run: echo "::set-output name=test::hello"
      # - name: deploy infra
      #   id: deploy_infra
      #   run: |
      #     az group create --name csu-nl-sr-graphql --location westeurope
      #     echo "::set-output name=registry::$(az deployment group create --resource-group csu-nl-sr-graphql --template-file ./deployment/infra/main.bicep --query properties.outputs.containerRegistryName.value)"
  deploy_apps:
    runs-on: ubuntu-latest
    needs: deploy_infra
    
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - run: echo ${{needs.deploy_infra.outputs.registry}}
      # - name: upload containers
      #   run: |
      #     ./deployment/apps/upload_docker_images.sh ${{needs.deploy_infra.outputs.registry}} 
      # - name: deploy container apps
      #   id: deploy_apps
      #   run: |
      #     echo "::set-output name=graph_endpoint::$(az deployment group create --resource-group csu-nl-sr-graphql --template-file ./deployment/apps/main.bicep --query properties.outputs.graphqlEndpoint.value)"

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install requirements and retrieve schema
        run: |
          npm install -g get-graphql-schema
          echo $(az deployment group show -g csu-nl-sr-graphql -n main --query properties.outputs.graphqlEndpoint.value)
          ./deployment/apps/upload_graphql_schema.sh ${{env.RESOURCE_GROUP}}
      - name: upload schema
        run: |
          az apim api schema create \
            --service-name $(az deployment group show -g csu-nl-sr-graphql -n main --query properties.outputs.apimName.value) \
            -g ${{ env.RESOURCE_GROUP }} \
            -n main \
            --api-id $(az deployment group show -g ${{ env.RESOURCE_GROUP }} --query properties.outputs.apiId.value) \
            --schema-id graphql \
            --schema-type application/vnd.ms-azure-apim.graphql.schema \
            --schema-path ./schema.graphql