on:
  push:
    branches:
      - main
    
jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      registry_name: ${{ steps.deploy_infra.outputs.registry }}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: step1
        run: echo "::set-output name=test::hello"
      - name: deploy infra
        id: deploy_infra
        run: |
          az group create --name csu-nl-sr-graphql --location westeurope
          REGISTRY=${az deployment group create --resource-group csu-nl-sr-graphql --template-file ./deployment/infra/main.bicep --query properties.outputs.containerRegistryName.value}
          echo "::set-output name=registry::${{REGISTRY}}"
  deploy_apps:
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: echo ${{needs.deploy_infra.outputs.registry_name}}
      - name: upload containers
        run: |
          ./deployment/apps/upload_docker_images.sh ${{needs.deploy_infra.outputs.registry_name}} 
      - name: deploy container apps
        run: |
          az deployment group create --resource-group csu-nl-sr-graphql --template-file ./deployment/apps/main.bicep